### ISSUE TITLE
What is the value for event in this schema?

### ISSUE THREAD

**Issue by maximillianus** [snowplow/iglu-central#1007]
https://github.com/snowplow/iglu-central/blob/72b641a24501390c73b0650352341ceaa1365c03/jsonpaths/com.mailgun/message_delivered_1.json#L13

Hi, I would like to know the value for event in this schema since my mailgun message_delivered data does not have this `event` column in its payload.

I can share with you anonymised payload data:
```
{
    "schema": {
        "vendor": "com.mailgun",
        "name": "message_delivered",
        "format": "jsonschema",
        "version": "1-0-0"
    },
    "data": {
        "recipient": "abc@gmail.com",
        "messageHeaders": "[[\"X-Mailgun-Sending-Ip\", \"111.111.111.111\"], [\"X-Mailgun-Sid\", \"xxx=\"], [\"Received\", \"by solar.mailgun.net with HTTP; Mon, 07 Oct 2019 00:40:18 +0000\"], [\"Date\", \"Mon, 07 Oct 2019 00:40:18 +0000\"], [\"Sender\", \"hello=hello@hello.com\"], [\"Message-Id\", \"xxx\"], [\"X-Mailgun-Template-Name\", \"welcome\"], [\"To\", \"abc@gmail.com\"], [\"From\", \"Hello <hello@hello.com>\"], [\"Subject\", \"Welcome to Hello\"], [\"Mime-Version\", \"1.0\"], [\"Content-Type\", [\"multipart/alternative\", {\"boundary\": \"xxx\"}]]]",
        "timestamp": "2019-10-07T00:40:24.000Z",
        "eventTimestamp": "1570408821.29",
        "domain": "mail.gmail.com",
        "signature": "xxx",
        "token": "xxx",
        "messageId": "xxx",
        "xMailgunSid": "xxx"
    },
    "hierarchy": {
        "rootId": "db821239-8855-4479-a805-6101d7308d8c",
        "rootTstamp": "2019-10-07 00:40:26.891",
        "refRoot": "events",
        "refTree": ["events", "message_delivered"],
        "refParent": "events"
    }
}
```

If it is still relevant, then that is fine, maybe I can know what is the value so I can fill up mock value for my data.

If it is not relevant anymore, can we update it?

**Comment by chuwy** [comment]
Hi @maximillianus. There's no value for `event`. As per [its schema](https://github.com/snowplow/iglu-central/blob/72b641a24501390c73b0650352341ceaa1365c03/schemas/com.mailgun/message_delivered/jsonschema/1-0-0) all values are optional (not listed in `required` schema property)

Also please direct all support questions to [our forums](https://discourse.snowplowanalytics.com/). You'll get a response there much faster. Our github is for bugreports and feature requests only.

Thanks!
