### ISSUE TITLE
missing enum value 'cell' for `networkType` properties in mobile_context

### ISSUE THREAD

**Issue by gautam-yoti** [snowplow/iglu-central#1018]
We are seeing following errors in bad bucket: 
`error: instance value (\"cell\") not found in enum (possible values: [\"mobile\",\"wifi\",\"offline\"])\n    level: \"error\"\n    schema: {\"loadingURI\":\"#\",\"pointer\":\"/properties/networkType\"}\n    instance: {\"pointer\":\"/networkType\"}\n    domain: \"validation\"\n    keyword: \"enum\"\n    value: \"cell\"\n    enum: [\"mobile\",\"wifi\",\"offline\"]\n`

For following schema: iglu:com.snowplowanalytics.snowplow/mobile_context/jsonschema/1-0-1

Here's the link in which I think we need to include "cell" as a enum to fix this issue: 
https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/mobile_context/jsonschema/1-0-1#L29

**Comment by colmsnowplow** [comment]
@gautam-yoti is there a reason that `cell` is required as distinct from `mobile`?

**Comment by colmsnowplow** [comment]
@gautam-yoti could you clarify which tracker and version the data in question came from?

**Comment by gautam-yoti** [comment]
tna: ios-0.9.0
osVersion: 13.x.x/12.x.x
mostly seeing events flooding for iOS tracker

**Comment by gautam-yoti** [comment]
Reply from support team, 

We have checked this with our Engineering team and this should be fixed in version 1.0.3. But we would like to suggest you to take this opportunity and upgrade straight to the latest iOS tracker version: 1.1.5.

Of course, users with the old app will continue to send bad events until they update their app with latest tracker version.

**Comment by colmsnowplow** [comment]
Thanks for the follow-up @gautam-yoti , you beat me to the punch!
