### ISSUE TITLE
Add org.ietf/http_client_hints/jsonschema/1-0-0 

### ISSUE THREAD

**Issue by paulboocock** [snowplow/iglu-central#1061]
Chrome 84 will add a new feature calls User Agent Client Hints. This is in preparation for freezing the User Agent string in the near future.

This schema will allow us to collect the new Client Hints as outlined here: https://tools.ietf.org/html/draft-ietf-httpbis-client-hints-15

The values are available in JavaScript as detailed here: https://wicg.github.io/ua-client-hints/#getters

This will be added to the JavaScript 2.15.0 release.

**Comment by ihortom** [comment]
@paulboocock / @chuwy , could the rest of the static files be added as well please, namely SQL and JSONPaths? Not everyone has automigration in place.
