### ISSUE TITLE
Wrong schema versions in com.snowplowanalytics.snowplow.storage/redshift_config

### ISSUE THREAD

**Issue by andrewhabib** [snowplow/iglu-central#1071]
Hi, 

In [com.snowplowanalytics.snowplow.storage/redshift_config](https://github.com/snowplow/iglu-central/tree/master/schemas/com.snowplowanalytics.snowplow.storage/redshift_config/jsonschema), there are wrong increments of schema versions which do not respect the [SchemaVer](https://snowplowanalytics.com/blog/2014/05/13/introducing-schemaver-for-semantic-versioning-of-schemas/).

**1) 2-0-0 to 2-1-0**
This change is fully backward compatible because:
- Existing `password` field is expanded from `"type": "string"` to `"type": ["string", "object"]`
- A new key `sshTunnel` is added but `additionalProperties` was `False`

So nothing breaks backward compatibility and the proper new schema version should be 2-0-1, not 2-1-0

**2) 3-0-0 to 4-0-0** 
This change is fully backward compatible because:
- A new key `blacklistTabular` is added but  `additionalProperties` was `False`

So nothing breaks backward compatibility and the proper new schema version should be 3-0-1, not 4-0-0

**Comment by chuwy** [comment]
Closing as per https://github.com/snowplow/iglu-central/issues/1072#issuecomment-674085232
