### ISSUE TITLE
Wrong schema version in com.snowplowanalytics.snowplow/geolocation_context

### ISSUE THREAD

**Issue by andrewhabib** [snowplow/iglu-central#1073]
Hi again, 

In [com.snowplowanalytics.snowplow/geolocation_context](https://github.com/snowplow/iglu-central/tree/master/schemas/com.snowplowanalytics.snowplow/geolocation_context/jsonschema), there is a wrong increment of the schema version from 1-0-0 to 1-1-0 which does not respect the [SchemaVer](https://snowplowanalytics.com/blog/2014/05/13/introducing-schemaver-for-semantic-versioning-of-schemas/).

The change from version 1-0-0 to version 1-1-0 is fully backward compatible:
- All existing fields are expanded to be `"type": ["number", "null"]` instead of `"type": "number"`
- A new key `timestamp` is added but `additionalProperties` was `False`

So nothing breaks backward compatibility and the proper new schema version should be 1-0-1, not 1-1-0.

**Comment by chuwy** [comment]
Closing as per https://github.com/snowplow/iglu-central/issues/1072#issuecomment-674085232
