### ISSUE TITLE
Schema for a com.twitter/lzo_raw_array

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu-central#118]
Name needs tweaking - but I'm talking about the Protocol Buffer array of Bytes. I think I've seen the Protocol Buffers IDL embedded in some Twitter code somewhere...

**Comment by fblundun** [comment]
I think this was the embedded IDL you saw: https://github.com/twitter/elephant-bird/blob/94aa4a7dd250457bf231fdac6ab5e12a987263c0/core/src/main/java/com/twitter/elephantbird/mapreduce/io/SerializedBlock.java#L19-L23

**Comment by alexanderdean** [comment]
That's the one!

**Comment by alexanderdean** [comment]
Can we call Protocol Buffers ".../protobuf/..." similar to how Google do it https://github.com/google/protobuf
