### ISSUE TITLE
Add nl.basjes/yauaa_context/jsonschema/1-0-4

### ISSUE THREAD

**Issue by dilyand** [snowplow/iglu-central#1216]
The YAUAA enrichment can fail (produce bad rows) for certain valid useragent strings, where the `webviewAppNameVersionMajor` exceeds 50 characters.

Example: `Mozilla/5.0 EmbeddedBrowser (Linux; Android 10; SM-A202F Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36 DeviceUID: c3df64e9-f56e-4ede-b20e-f792196a8ee4 VendorUID: 7b16065e-78d9-d15a-8cb9-ae24c60cc55b`

This seems to be a case where the limit should have been longer to begin with, because `webviewAppNameVersionMajor` is a concatenation of `webviewAppName` and `webviewAppVersionMajor`. In the 1-0-3 webviewAppName is unlimited and webviewAppVersionMajor is also limited to 50. So the concatenation should probably already have accepted a higher limit.

But it also points to a larger issue with the schema, which we've seen before, eg in #1126. The useragent is a very dynamic string, which can vary dramatically between implementations. Occasionally, we run the risk falling afoul of one or another vendor's limitations.

For version 1-0-4 it might be a good idea to relax the schema more generally (not just this one offending field). There are a number of properties with limits of between 50 and 100 that all seem high-risk for a future breakage along the same lines. We could extend all of them to 1,024, which appears quite generous.

At the same time, there are many properties in the schema that have no limitations at all. Perhaps we should move to removing all max lengths to keep things consistent? Introducing limits to these fields would be a backward incompatible change, so unless there's a very good reason for it, we should probably avoid that.

Also, for context, none of the limitations are imposed by YAUAA or any official useragent specification. They are just best guesses about what is reasonable.

**Comment by AlexBenny** [comment]
Sounds sensible. I tag @snowplow/com-snowplowanalytics-engineering-datavalue-integrations  for a feedback on this about data modelling.

**Comment by agnessnowplow** [comment]
I don't see this issue anymore from a datamodeling point of view. There used to be a limitation within the Snowflake sql runner web model on the yauaa fields but it has already been removed: https://github.com/snowplow/data-models/issues/97 The rest of the supported warehouses and the dbt web model does not impose limits on these fields regarding the VARCHAR length.

**Comment by dilyand** [comment]
In [this `atomic.events` table definition reference](https://github.com/snowplow/snowplow-rdb-loader/blob/master/modules/snowflake-loader/src/main/resources/atomic-def.sql#L108), the overall length of the `useragent` string is limited to 1,000. So no constituent part can be longer than that. I think this is a good limit for all properties in this schema that are directly extracted (rather than deduced) from the useragent string.
