### ISSUE TITLE
Add missing cs-uri-stem field to the wd_access_log schemas

### ISSUE THREAD

**Issue by fblundun** [snowplow/iglu-central#127]
There's a cs-uri-stem field in the [regex](https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/loaders/CloudfrontLoader.scala#L65) but not the schemas. Is it excluded due to being a substring of the cs(Host) field?

**Comment by alexanderdean** [comment]
Hmm, I think that must be a bug _in the schema_...
