### ISSUE TITLE
Add com.snowplowanalytics.snowplow/desktop_context

### ISSUE THREAD

**Issue by duncan** [snowplow/iglu-central#129]
We’ve ported the iOS client to run on Mac and need to either use a mobile_context or have a new desktop_context. We propose the following properties on a desktop_context schema:

- osType
- osVersion
- deviceManufacturer
- deviceModel

This is a subset of the mobile_context, but without the IDFA and IDFV stuffs. Thanks!

**Comment by alexanderdean** [comment]
This sounds like a very sane starting point. @yalisassoon does this look good to you...

**Comment by yalisassoon** [comment]
Looks great!

**Comment by duncan** [comment]
👏
