### ISSUE TITLE
Make geolocation_context's timestamp an integer value?

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu-central#138]
I'm guessing it's not a float...

**Comment by alexanderdean** [comment]
This looks to be correct: http://www.w3.org/TR/DOM-Level-3-Core/core.html#Core-DOMTimeStamp

@fblundun can you see any issues with making this change?

**Comment by fblundun** [comment]
I've made this change in the above commit. I also fixed the version (it should be 1-1-0 rather than 1-0-1), and a typo ("timestampe"). So the JavaScript Tracker's geolocation_context cannot be used unless the above fix is released...

**Comment by alexanderdean** [comment]
Thanks Fred, I am going to release r31 for Iglu Central this morning, so we can release the JS Tracker after that...
