### ISSUE TITLE
Change type of numeric fields in ua_parser_context to string

### ISSUE THREAD

**Issue by fblundun** [snowplow/iglu-central#147]
Rather than string.

Sample value: "Windows XP"

**Comment by alexanderdean** [comment]
Good catching, scheduling

**Comment by fblundun** [comment]
There's a mismatch between the schema and the enrichment: in the JSON generated by the enrichment the version fields are strings like `"4"`, but the schema expects numbers like `4`.

Example of JSON generated by enrichment:

```json
{
  "user_agent": {
    "family": "Mobile Safari",
    "major": "5",
    "minor": "1",
    "patch": null
  },
  "os": {
    "family": "iOS",
    "major": "5",
    "minor": "1",
    "patch": "1",
    "patch_minor": null
  },
  "device": {
    "family": "iPhone"
  }
}
```

Should we change the enrichment or the schema?

**Comment by alexanderdean** [comment]
What's the underlying type in ua_parser? We should go with that...

**Comment by fblundun** [comment]
The underlying type generated by ua_parser is string rather than number. So I'll change the schema rather than the enrichment.

**Comment by alexanderdean** [comment]
Thanks Fred!
