### ISSUE TITLE
Schema for a com.snowplowanalytics.monitoring/stream_write_failed event

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu-central#149]
Fred! While you are thinking about back-off and retry for Scala Kinesis Enrich, could you draft up an event to model a put failure?

Have a think of what fields would be useful to record in this event (this will be emitted by Snowplow)...

**Comment by fblundun** [comment]
Here are some potential fields:

timestamp
retryCount
errorType
errorMessage
streamName
putSize (number of records in the PutRecords request)
appName (e.g. scala-stream-collector-0.5.0)
appId (e.g. ssc-live-1 - this field doesn't exist yet)

Maybe something like "lastCheckpoint" for applications which also read from a stream?
Should we include the actual contents of the records in the failure event?

**Comment by alexanderdean** [comment]
Thanks Fred! Great list. I think timestamp we get anyway so that's okay.

I think "lastCheckpoint" is too specific - assumes too much about how the app works (e.g. what if it is joining events from two streams?)

I don't think we should include the actual records in the failure - we should think of an event like this as control flow, not data flow...

**Comment by fblundun** [comment]
That all makes sense. Similarly to getting the timestamp for free, we can also get the appId field for free.
