### ISSUE TITLE
Add com.mparticle.snowplow/transaction_event 1-0-0

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu-central#167]

**Comment by Aerlinger** [comment]
It seems to already exist on S3 here: http://s3.amazonaws.com/snowplow-hosted-assets-us-east-1/4-storage/redshift-storage/jsonpaths/com.mparticle.snowplow/transaction_event_1.json.

**Comment by alexanderdean** [comment]
Correct, but it's not in master yet.

**Comment by alexanderdean** [comment]
Done, closing
