### ISSUE TITLE
Add schema for a sink_write_failed event

### ISSUE THREAD

**Issue by fblundun** [snowplow/iglu-central#172]
Suggestions for a better name are welcome...

This is the event that the ES sink would send when it has made several failed attempts to connect to the ES cluster.

Possible fields:

- What is failing (e.g. "elasticsearch_connection" or "s3_connection")
- Number of failed connection attempts so far
- Time of first failure
- Exception message

**Comment by alexanderdean** [comment]
This sounds good! I like the possible fields. Possible name: elasticsearch_write_failed

**Comment by alexanderdean** [comment]
Another field could be last_retry_period

**Comment by fblundun** [comment]
last_retry_period sounds good. How about calling the schema "connection_failing"? Then it isn't specific to any particular endpoint.

**Comment by alexanderdean** [comment]
I like the idea of making it not sink specific! But think connection may be too specific in a different way. What about "sink_write_failed"?

**Comment by fblundun** [comment]
Another question: are we going to keep trying to send to the sink after we have sent the monitoring event?

If we are then there should probably be some sort of sink_write_succeeded event, similar to how monitor-kinesis can cancel pager duty alerts.

**Comment by fblundun** [comment]
We decided to send a sink_write_failed event on every failure and take the absence of sink_write_failed events to mean that the sink is available again.
