### ISSUE TITLE
Add client_session context

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu-central#180]
Fields:

1. session_id
2. session_index

Anything else we should add in here @yalisassoon ? Only thing I can think of could be `previous_session_id` which might be nice for pathing in JOIN-less environments...

**Comment by alexanderdean** [comment]
I'm wondering if we should add a user_id in here, which will be the domain_userid following migration.

**Comment by alexanderdean** [comment]
I'm wondering if we should document the local storage type used too, e.g. "sqllite" versus "cookie" versus "localStorage" versus "flashCookie". That way you could even send multiple instances of this context (stored in different local storage) with the same event...

**Comment by alexanderdean** [comment]
This is what I've got so far:

```json
{
  "type": "object",
  "properties": {
    "userId": {
      "type": "string",
      "format": "uuid"
    },
    "sessionId": {
      "type": "string",
      "format": "uuid"
    },
    "sessionIndex": {
      "type": "integer",
      "minimum": 0,
      "maximum": 2147483647
    },
    "previousSessionId": {
      "type": "string",
      "format": "uuid"
    }
  },
  "additionalProperties": false
}
```

It still needs to be updated to support JS Tracker's legacy session and user IDs.

@fblundun - could you share a regexp that all session and user IDs generated by the JS Tracker conform to?

**Comment by fblundun** [comment]
Session IDs are all UUIDs conforming to `[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}`.

Domain user IDs are currently 16 hexadecimal characters, i.e. `[0-9a-f]{16}`, but will eventually also become a UUID, due to https://github.com/snowplow/snowplow-javascript-tracker/issues/274. In both cases they will conform to `^[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$|^[0-9a-f]{16}$`.

**Comment by alexanderdean** [comment]
@yalisassoon, @bogaert - feedback on the above schema please? The plan is for this to be used in the Android Tracker, then the iOS Tracker, and ultimately it will replace the existing domain session fields in the JS Tracker / Tracker Protocol...

**Comment by bogaert** [comment]
@alexanderdean – Looks good to me. I like that the previous session ID will be included. Is there a reason not to include a local storage field?

**Comment by alexanderdean** [comment]
Hey @bogaert - great stuff. I have added in a new field "storageMechanism", agree it could be useful!
