### ISSUE TITLE
Add jobflow_step_status context schema

### ISSUE THREAD

**Issue by fblundun** [snowplow/iglu-central#195]

**Comment by fblundun** [comment]
It could have the name, state, created_at, started_at, and ended_at fields which are accessible via Elasticity: https://github.com/rslifka/elasticity/blob/master/lib/elasticity/job_flow_status_step.rb

**Comment by alexanderdean** [comment]
Sounds great. An array of jobflow_step_status'es can be sent on any jobflow success or failure
