### ISSUE TITLE
Patch com.callrail/call_complete to allow for device_type

### ISSUE THREAD

**Issue by digitaltouch** [snowplow/iglu-central#279]
It appears that device_type was added to the POST body and query string without any information on the CallRail website.  We are not sure what this field contains, when it contains a value, and what type of value that it contains.  We are reaching out to CallRail for more information.

An example of the POST Body that we received is below:

`{"id":1111111111,"datetime":"2015-12-30 05:03:19","trackingnum":"+19999989999","callernum":"+19999989999","destinationnum":"9999989999","callsource":"disabled","callername":"Wireless Caller","callercity":"None","callerstate":"TX","callerzip":"","callercountry":"US","keywords":"","referrer":"","referrermedium":"","landingpage":"","transcription":"","gclid":"","ip":"","utm_source":"offline","utm_medium":"(none)","utm_term":"","utm_content":"","utm_campaign":"test","first_call":false,"device_type":null,"custom":{},"recording":"","answered":false,"duration":"22","recording_player":"","tag":"","tags":[],"note":""}`

The device_type is also included in the query string, but the adapter seems to be ignoring. 

The error generated during the enrichment phase is below:

`"errors":[{"level":"error","message":"error: object instance has properties which are not allowed by the schema: [\"device_type\"]\n    level: \"error\"\n    schema: {\"loadingURI\":\"#\",\"pointer\":\"\"}\n    instance: {\"pointer\":\"\"}\n    domain: \"validation\"\n    keyword: \"additionalProperties\"\n    unwanted: [\"device_type\"]\n"}],"failure_tstamp":"2015-12-30T01:11:01.821Z"`

Added device_type to the schema in our fork of iglu-central.  Set the vendor prefix for com.callrail to point to our hosted Iglu repository, and it still seems to be pointing to the iglu-central version (same error).  Am I interpreting that functionality correctly?  

We have yet to see a value for device_type passed by CallRail that is not set to null. Once we understand what is being passed here, we will update the Redshift DDL accordingly.

**Comment by alexanderdean** [comment]
Hi @digitaltouch - thanks for raising.

> Added device_type to the schema in our fork of iglu-central. Set the vendor prefix for com.callrail to point to our hosted Iglu repository, and it still seems to be pointing to the iglu-central version (same error). Am I interpreting that functionality correctly? 

Your understanding is correct. Note that you don't need a full copy of Iglu Central in your fork - just the schema you are trying to patch. Something like this should do it:

```json
{
  "schema": "iglu:com.snowplowanalytics.iglu/resolver-config/jsonschema/1-0-0",
  "data": {
    "cacheSize": 500,
    "repositories": [
      {
        "name": "Iglu Central",
        "priority": 0,
        "vendorPrefixes": [
          "com.snowplowanalytics"
        ],
        "connection": {
          "http": {
            "uri": "http://iglucentral.com"
          }
        }
      },
      {
        "name": "digitalpoint Iglu",
        "priority": 0,
        "vendorPrefixes": [
          "com.callrail",
          "com.digitaltouch"
        ],
        "connection": {
          "http": {
            "uri": "https://xxx"
          }
        }
      }
    ]
  }
}
```

Ultimately we will have to make a decision on whether to patch this schema (because our original understanding of the schema was incomplete) or add a 1-0-1 (because the schema has evolved).

**Comment by digitaltouch** [comment]
Thanks for the clarification. 

I had already pointed com.callrail in the vendorPrefix of our resolver.config and it still seems to be loading the iglu-central version. Any ideas?

**Comment by alexanderdean** [comment]
No idea, sorry - the test suite for the Iglu Scala Client (which Enrichment uses) validates the correct behavior:

https://github.com/snowplow/iglu-scala-client/blob/master/src/test/scala/com.snowplowanalytics.iglu.client/ResolverSpec.scala#L78

**Comment by digitaltouch** [comment]
@alexanderdean Thanks for the help.  Got it to work, there were conflicting priorities in the resolver file.  

call_complete events are now successfully being enriched / shredded. We will keep an eye out for any more information from CallRail in order to make a decision on the schema version.

**Comment by alexanderdean** [comment]
Glad to hear you got it working - keep us posted...

**Comment by digitaltouch** [comment]
According to call rail the device_type was added on 11/30/2015, which is after the initial check in date of the 1-0-0 schema.  Bumping schema version to 1-0-1.

**Comment by alexanderdean** [comment]
Replaced by #281, closing...
