### ISSUE TITLE
Patch com.amazon.aws.ec2/instance_identity_document/jsonschema/1-0-0 to reflect new ID format

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu-central#280]
Amazon announced that new Instance IDs will be longer than 10 characters. Our Schema [assumes](https://github.com/snowplow/iglu-central/blob/master/schemas/com.amazon.aws.ec2/instance_identity_document/jsonschema/1-0-0#L12-L14) it has 10 characters. Will kernel id, ramdisk id etc remain same length?

**Comment by alexanderdean** [comment]
Pushing back...
