### ISSUE TITLE
Patch org.w3/PerformanceTiming/jsonschema/1-0-0

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/iglu-central#293]
Sometimes the context returns no data e.g.:

```json
{
	"schema": "iglu:org.w3/PerformanceTiming/jsonschema/1-0-0",
	"data": {}
}
```

We should therefore remove the [minProperties constraint](https://github.com/snowplow/iglu-central/blob/master/schemas/org.w3/PerformanceTiming/jsonschema/1-0-0#L144) so that events with these blank contexts do not fail validation

**Comment by fblundun** [comment]
@yalisassoon do you know what useragent(s) this happens with?
