### ISSUE TITLE
Schema for a com.amazon.aws.lambda/java_context/jsonschema/1-0-0

### ISSUE THREAD

**Issue by ninjabear** [snowplow/iglu-central#309]
Schema for an [AWS lambda context](http://docs.aws.amazon.com/lambda/latest/dg/java-context-object.html)

**Comment by alexanderdean** [comment]
Removed "event" from end of ticket name

**Comment by alexanderdean** [comment]
@ninjabear I'm not seeing the PR?

**Comment by ninjabear** [comment]
hey @alexanderdean - raised that now https://github.com/snowplow/iglu-central/pull/310
