### ISSUE TITLE
Patch com.snowplowanalytics.snowplow.enrichments/api_request_enrichment_config/jsonschema/1-0-0 to add JSONPath validation

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu-central#316]
Unfortunately, we cannot provide any strict JSONPath validation and I decided to not short-circuit enrichment on parsing invalid JSONPath as it won't give user any helpful error message.

Hence, I think it would be good to add at least `"pattern": "^\\$.*$"` (I think it is always valid for our use case), so users won't at least confuse JSONPath with `jq` syntax or similar tools.

**Comment by alexanderdean** [comment]
Sounds good, please make this happen...
