### ISSUE TITLE
Add com.amazon.aws.lambda/s3_notification_event/jsonschema/1-0-0

### ISSUE THREAD

**Issue by ninjabear** [snowplow/iglu-central#322]

**Comment by alexanderdean** [comment]
@ninjabear can you do a PR into snowplow/snowplow for the JSON Paths and the SQL file? Please use latest version of Schema Guru (0.6.1)

**Comment by ninjabear** [comment]
@alexanderdean sure - https://github.com/snowplow/snowplow/pull/2591
