### ISSUE TITLE
Patch com.snowplowanalytics.snowplow.enrichments/api_request_enrichment_config/jsonschema/1-0-0 to allow just vendor-name-format criterion

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu-central#327]

**Comment by alexanderdean** [comment]
Scheduling

**Comment by chuwy** [comment]
I also fixed tabs and strengthened patterns according to https://github.com/snowplow/iglu-central/issues/288.

**Comment by alexanderdean** [comment]
Thanks @chuwy ! Do we need to make a complementary change to the snowplow/snowplow code, or is it just this change?

**Comment by chuwy** [comment]
Yes, we need to make a change to snowplow/snowplow (haven't pushed it yet).

**Comment by chuwy** [comment]
Pushed.

**Comment by alexanderdean** [comment]
Hey @chuwy - thanks for the push - can you also update the M and rcs in snowplow/snowplow for testing?

**Comment by chuwy** [comment]
@alexanderdean updated.
