### ISSUE TITLE
Fix invalid non-Iglu $schema keywords in enrichments configurations

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu-central#378]
Following JSON Schemas (all except first one are Snowplow enrichments) have common Draft v4 `$schema` rather than ours:

 * com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0 (I think it should be self-referenced or hosted separately, without self-describing info)
 * com.snowplowanalytics.snowplow/anon_ip/jsonschema/1-0-0
 * com.snowplowanalytics.snowplow/campaign_attribution/jsonschema/1-0-0
 * com.snowplowanalytics.snowplow/campaign_attribution/jsonschema/1-0-1
 * com.snowplowanalytics.snowplow/cookie_extractor_config/jsonschema/1-0-0
 * com.snowplowanalytics.snowplow/enrichments/jsonschema/1-0-0
 * com.snowplowanalytics.snowplow/event_fingerprint_config/jsonschema/1-0-0
 * com.snowplowanalytics.snowplow/ip_lookups/jsonschema/1-0-0
 * com.snowplowanalytics.snowplow/javascript_script_config/jsonschema/1-0-0
 * com.snowplowanalytics.snowplow/referer_parser/jsonschema/1-0-0
 * com.snowplowanalytics.snowplow/uri_redirect/jsonschema/1-0-0
 * com.snowplowanalytics.snowplow/user_agent_utils_config/jsonschema/1-0-0
 * com.snowplowanalytics.snowplow.enrichments/api_request_enrichment_config/jsonschema/1-0-0
 * com.snowplowanalytics.snowplow.enrichments/http_header_extractor_config/jsonschema/1-0-0
 * com.snowplowanalytics.snowplow.enrichments/sql_query_enrichment_config/jsonschema/1-0-0
 * com.snowplowanalytics.snowplow.enrichments/weather_enrichment_config/jsonschema/1-0-0
 * com.snowplowanalytics.snowplow.input-adapters/segment_webhook_config/jsonschema/1-0-0

Following JSON Schemas have no `$schema` keyword yet include self-describing info:

 * com.snowplowanalytics.iglu/anything-a/jsonschema/1-0-0
 * com.snowplowanalytics.iglu/anything-b/jsonschema/1-0-0
 * com.snowplowanalytics.iglu/anything-c/jsonschema/1-0-0

Users (and we) tend to treat `$schema` not seriously enough.

@alexanderdean do we need separate tickets for each patch?

**Comment by alexanderdean** [comment]
Hey @chuwy - we can do a single commit for each group of fixes (I count two or three distinct fixes in your list). But we need to list all the patched schemas in the CHANGELOG of course.

I didn't understand:

> com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0 (I think it should be self-referenced or hosted separately, without self-describing info)

If it's hosted separately, then it won't be available at the Iglu Central path referenced by so many other schemas. Could you set out some possible options here?

**Comment by chuwy** [comment]
I actually think that self-referencing is the right way. That is what Draft v4 schema does.

**Comment by alexanderdean** [comment]
Let's do it - so can you split this ticket into 3?

**Comment by chuwy** [comment]
Done.
