### ISSUE TITLE
Allow null in optional payload_data fields

### ISSUE THREAD

**Issue by bogaert** [snowplow/iglu-central#630]
An event now fails validation when it's sent with `uid: null`. We have seen this happen with events from the Android tracker, perhaps other trackers allow `setUserId(null)` too.

Related to:

- https://github.com/snowplow/iglu/issues/231
- https://github.com/snowplow/snowplow-android-tracker/issues/250

**Comment by alexanderdean** [comment]
No, this isn't how payload_data is conceived - payload_data is based on the concept of a GET querystring of name-value pairs - where a value is either there as a string (even an empty string), or the whole name-value is not set. There is no concept of a null value in a GET querystring, so there is no concept of null in payload_data.

This is a bug in the Android Tracker, closing.
