### ISSUE TITLE
Schema validation is failing 

### ISSUE THREAD

**Issue by apiautoamtion** [snowplow/iglu-central#633]
Response:
"header": {
        
    },
Schema error:
est execution Failed :- com.github.fge.jsonschema.core.exceptions.InvalidSchemaException: fatal: invalid JSON Schema, cannot continue
Syntax errors:
[ {
  "level" : "error",
  "schema" : {
    "loadingURI" : "target/test-classes/TopSeller.json#",
    "pointer" : "/properties/header/properties/description"
  },
  "domain" : "syntax",
  "message" : "JSON value is of type string, not a JSON Schema (expected an object)",
  "found" : "string"
}, {
  "level" : "error",
  "schema" : {
    "loadingURI" : "target/test-classes/TopSeller.json#",
    "pointer" : "/properties/header/properties/id"
  },
  "domain" : "syntax",
  "message" : "JSON value is of type string, not a JSON Schema (expected an object)",
  "found" : "string"
}, {
  "level" : "error",
  "schema" : {
    "loadingURI" : "target/test-classes/TopSeller.json#",
    "pointer" : "/properties/header/properties/title"
  },
  "domain" : "syntax",
  "message" : "JSON value is of type string, not a JSON Schema (expected an object)",
  "found" : "string"
} ]
    level: "fatal"

**Comment by apiautoamtion** [comment]
Response is  empty object but getting mismatch declaration type

Please help me to resolve this issue

**Comment by apiautoamtion** [comment]
Schema file : "header": {
      "id": "/properties/header", 
      "properties": {
        "description": "This accepts anything, as long as it's valid JSON.", 
        "id": "/properties/header/properties", 
        "title": "Empty Object"
      }, 
      "type": "object"  
    },

**Comment by alexanderdean** [comment]
Iglu Central is a repo of JSON Schemas - I can't see a connection between your issue above and Iglu Central, closing...
