### ISSUE TITLE
Patch com.snowplowanalytics.snowplow/mobile_context/jsonschema/1-0-0

### ISSUE THREAD

**Issue by ihortom** [snowplow/iglu-central#673]
We have come across a scenario when a device can produce no `carrier` resulting in `null` sent down the pipeline. Could we host an updated version of `mobile_context` with a relaxed restriction?

The changes required

```
"carrier": {
    "type": ["string", "null"]
}
```

No changes to SQL and jsonpaths.

**Comment by alexanderdean** [comment]
Thanks @ihortom , can you open the PR please?

**Comment by alexanderdean** [comment]
Duplicate of #674

**Comment by alexanderdean** [comment]
Whoops, re-opening
