### ISSUE TITLE
Infrastructure: extend push.bash to handle JSON Paths files 

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu-central#678]
### Background

To support loading these records into Redshift, the JSON Paths files [found in this repo](https://github.com/snowplow/iglu-central/tree/master/jsonpaths) must be published (as publically accessible files) to Amazon S3.

Due to a limitation in Redshift's [`COPY FROM JSON` command](http://docs.aws.amazon.com/redshift/latest/dg/copy-usage_notes-copy-from-json.html), these JSON Paths files must be made available in an S3 bucket in the same region as the Redshift being loaded.

### Earlier solution

Historically, the JSON Paths files lived in the [snowplow/snowplow repo](), and there was a script in that repo designed to perform this sync process (but not the original deployment of the JSON Paths files). However, this script was removed when we changed how Snowplow artifacts are published to S3.

You can see the last version of the script here:

https://github.com/snowplow/snowplow/blob/3177968e579f2f7925e6a2b1c00dc2566046df1c/vagrant/push/sync-hosted-assets.bash

### Proposed solution

I propose that we extend `push.bash` to:

* Push (all) the JSON Paths files to the `s3://snowplow-hosted-assets` bucket
* Synchronize the JSON Paths files in `s3://snowplow-hosted-assets` to all the other regional buckets

**Comment by alexanderdean** [comment]
Hey @chuwy - I have put this in R83 as I want to close out R82 today, but can this be prioritised? This is blocking the wider adoption of R8x schemas by Snowplow users...

**Comment by chuwy** [comment]
Ok, will start to work on it ASAP.

**Comment by alexanderdean** [comment]
Bringing forwards

**Comment by chuwy** [comment]
- [ ] Deploy script running after successful `lint`
- [ ] Create ticket to add credentials to Travis, like https://github.com/snowplow/iglu/issues/159
- [ ] Script syncing jsonpaths to s3://snowplow-hosted-assets-sa-east-1/4-storage/redshift-storage/jsonpaths/
- [ ] Script syncing schemas (clarify path)
- [ ] Check what differences we currently have between repository work tree and buckets

**Comment by chuwy** [comment]
Hey @oguzhanunlu, check-list is above.

**Comment by alexanderdean** [comment]
Thanks both!

**Comment by alexanderdean** [comment]
By "Script syncing jsonpaths to s3://snowplow-hosted-assets-sa-east-1/4-storage/redshift-storage/jsonpaths/"

do you mean

"Script syncing jsonpaths to s3://snowplow-hosted-assets-${region}/4-storage/redshift-storage/jsonpaths/"

**Comment by chuwy** [comment]
@alexanderdean I actually wanted to sync regional buckets with `snowplow-hosted-assets` as a separate step, but I agree - it is better to upload them straight into each bucket. Fixing check-list.

**Comment by alexanderdean** [comment]
Cool - whatever you think best. We want the least fragile process possible!

**Comment by chuwy** [comment]
Hey @alexanderdean, do we need to extend this script to sync JSON Schemas to Iglu Central? If yes - what is the bucket name and is it available from account with hosted assets bucket?

**Comment by oguzhanunlu** [comment]
Oh, I thought we would sync to same buckets and same path (except ../jsonpaths/) . Let's continue per @alexanderdean 's view.

**Comment by alexanderdean** [comment]
Hey @chuwy - no, let's do the JSON Schema sync in a later phase (create a ticket). It's important to get that right, and it's easy for me to do as a manual step right now.

**Comment by chuwy** [comment]
Ok, thanks! @oguzhanunlu, could you please remove everything about `schemas` and let me know if I can test it.

**Comment by oguzhanunlu** [comment]
@chuwy, I just removed `schemas` related parts and you can test deployment after adding encrypted access keys of a new AWS user with enough permission.
