### ISSUE TITLE
Add support for private hosting to Iglu Central

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu-central#7]
Please +1 this ticket if you are interested in having a private account on Iglu Central (i.e. private schemas not stored in git / GETable by others).

**Comment by epylinkn** [comment]
:+1:

**Comment by alexanderdean** [comment]
Closing because:

1. Iglu registry resolution means there is no need to have all schemas in the same registry
2. Adding private hosting to Iglu Central would require moving Iglu Central from a static registry to a Scala server-based registry, and there are major ops and performance advantages in the static registry option
