### ISSUE TITLE
Patch com.snowplowanalytics.snowplow.enrichments/pii_enrichment_config/jsonschema/1-0-0

### ISSUE THREAD

**Issue by knservis** [snowplow/iglu-central#721]
com.snowplowanalytics.snowplow.enrichments/pii_enrichment_config/jsonschema/1-0-0

added in https://github.com/snowplow/iglu-central/issues/692 requires the addition of something like:
```
		"vendor": {
			"type": "string",
                        "default": "com.snowplowanalytics.snowplow.enrichments"
		},
		"name": {
			"type": "string",
                        "default": "pii_enrichment_config"
		},
```
In the required fields to work as expected. I am not certain whether a new version or replacing the existing version is the right thing @alexanderdean 
The current version will not work at all as far as I can tell as streaming enrich  (and presumably spark enrich) require the vendor and name fields but these are not allowed by the schema.

To be honest I don't understand the need for a name and vendor field in the instance of the config, since these are already contained in the "self" section of the config schema where the instance is pointing to.

**Comment by chuwy** [comment]
I don't think it really requires this additions. I see these `name` and `vendor` as long-standing artifacts of not-implemented enrichments architecture. 

Instead I'd create a ticket in snowplow/snowplow to:

1. Remove `vendor` and `name` from all configurations we have (+associated Iglu Central tickets)
2. Follow [storage loaders config model](https://github.com/snowplow/iglu-central/tree/master/schemas/com.snowplowanalytics.snowplow.storage), where all consumers (consumers are Loaders and EER for storages, and SCE for enrichments) care only about schema key when parsing configuration file. But also storage all configs have `name` (human-readable) and `id` (machine-readable)  properties that in this particular case should replace `name` and `vendor`.

**Comment by knservis** [comment]
We will patch this version as per @alexanderdean offline comments for now and lets open a ticket for the changes you suggest @chuwy

**Comment by alexanderdean** [comment]
Scheduling...

**Comment by alexanderdean** [comment]
@knservis are you okay to create the (un-milestoned) ticket per @chuwy's suggestion?

**Comment by knservis** [comment]
@alexanderdean Done https://github.com/snowplow/snowplow/issues/3614
