### ISSUE TITLE
Patch com.mandrill/message_clicked/jsonschema/1-0-1

### ISSUE THREAD

**Issue by wbradley93** [snowplow/iglu-central#928]
Large numbers of `message_clicked` events are being invalidated for having null `/location`, `/msg/clicks/{{idx}}/ua`, `/msg/opens/{{idx}}/ua`, and `/user_agent_parsed` properties, mostly coming from mobile app users with user agents that Mandrill doesn't properly handle.

**Comment by chuwy** [comment]
In order to take an effect, this should be a patch, not a new schema as 1-0-1 is hardcoded in SCE https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/adapters/registry/MandrillAdapter.scala#L70
